### ISSUE TITLE
Media encoder?

### ISSUE THREAD

**Issue by robbeman** [kisonay/craft-twig-imagebase64#3]
Not really an issue, but here it goes anyway:

Not sure if you should just go ahead and use the Adobe Media Encoder logo for your project. (Not really an issue to me, just wondering if you could get "in trouble" with this. Hope you don't mind me noticing. 😉)

**Comment by kisonay** [comment]
Thank you, I just picked any icon, but valid point. I will look to update it.

**Comment by kisonay** [comment]
https://github.com/kisonay/craft-twig-imagebase64/releases/tag/1.0.4

Icon changed
